### ISSUE TITLE
cargo build fail on M1 Mac Rust

### ISSUE THREAD

**Issue by kjur** [PaulJuliusMartinez/jless#30]
I got a error on cargo build:
```
% sudo cargo install jless
... snip ...
error[E0658]: or-patterns syntax is experimental
   --> /Users/user1/.cargo/registry/src/github.com-1ecc6299db9ec823/jless-0.7.1/src/app.rs:101:26
    |
101 |                 KeyEvent(Key::Ctrl('c') | Key::Char('q')) => break,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information
error[E0658]: or-patterns syntax is experimental
  --> /Users/user1/.cargo/registry/src/github.com-1ecc6299db9ec823/jless-0.7.1/src/jsonparser.rs:67:24
   |
67 |         while let Some(JsonToken::Whitespace | JsonToken::Newline) = self.peek_token_or_eof() {
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0658`.
error: failed to compile `jless v0.7.1`, intermediate artifacts can be found at `/tmp/cargo-installoCXkLq`
Caused by:
  could not compile `jless`
To learn more, run the command again with --verbose.
```

How can I build this? Thank you for your help.

**Comment by smbl64** [comment]
Which Rust version do you use? (`rustc --version`)?

From the error you have posted, it seems the `or-patterns` require at least Rust v1.53. 
(https://github.com/rust-lang/rust/issues/54883)

**Comment by kjur** [comment]
Thank you. My rustc version is "1.52.1". I'll update and try it.

**Comment by kjur** [comment]
Works fine with rust 1.58.1. Thank you for the cool tool.
